### PR TITLE
Fixes typo on window.TextPatcher

### PR DESCRIPTION
**Pull request by atmoio**

### CODE REVIEW

**Comment by ansuz** [comment]
thanks!

are you using textPatcher for your app, or were you just reviewing the code?

**Comment by atmoio** [comment]
Yes, just playing around with it and Chainpad. Chainpad is pretty cool! I got it working, but it doesn't work if I type really really fast. I'm guessing it has something to do with checkpoints, which I'm not yet understanding. If I don't figure it out, I'll post a question with what I'm doing and see if I'm missing something.

**Comment by ansuz** [comment]
That's great to hear!

If you're looking to build a zero knowledge app on top of chainpad, it'll probably be easiest to get support if you join our irc/matrix channel. Freenode#cryptpad

**Comment by atmoio** [comment]
Actually, figured it out. It was an issue with my implementation. Man, Chainpad is really cool. Felt magical when I got it working.

**Pull request merged**
